### ISSUE TITLE
Invalide date time when I upload file

### ISSUE THREAD

**Issue by francescacoo** [felixlen/ena_log#1]
Hi,
I am trying to check my exposure notification that I exported from Android, it finds 1 exposer and I do get error about invalid date time.
I can attach the file here if it helps?

**Comment by felixlen** [comment]
Hi Francesca,

this might be related to locale, currently I support German. Feel free to attach the log here or the mail me via fl@felixlenders.de in case of privacy concerns.

Best Felix

**Comment by francescacoo** [comment]
Hi Thanks a lot!
I have sent you the file via email.
My phone is in English indeed.
Maybe I could change the formatting to be as the German one if you can provide an example?
Thank you!

**Comment by felixlen** [comment]
Hi Francesca,

Thanks a lot for the sample. I will add support for Android log files in English over the weekend (probably this evening).

Best
Felix

**Comment by felixlen** [comment]
Can you please check if the fix works?

**Comment by francescacoo** [comment]
Yes it works thank you!
I am not sure if it should show something more, but I don't get the error anymore 
![Screenshot 2020-08-28 at 20 14 43](https://user-images.githubusercontent.com/1751355/91602206-377e0680-e96b-11ea-9219-8e697e7bc3ea.png)

**Comment by felixlen** [comment]
Hi Francesca,

The output is perfectly fine, as everything that contains no valuable information is filtered out.

What you can see here is that you had an encounter with a person that has been tested positive and the positive key is in the file from yesterday. Your phone checked this for the first time today 8:51 am and found one match in that file. Tomorrow you will see two entries in that table because that is the time your phone checks for the next time.
Your phone stores the encounters for 14 days, so once the number of matches drops from 1 to 0, you know that you had the encounter 14 days in advance.

Best
Felix

**Comment by felixlen** [comment]
Closed via e9de9b30bd4b497b80ffc7abd9f5037a977e59d7.

**Comment by francescacoo** [comment]
Hi Felix, is not recognizing september 
![Screenshot 2020-09-02 at 09 28 53](https://user-images.githubusercontent.com/1751355/91944727-d6558a80-ecfe-11ea-8b6d-63bd9425920d.png)
I will send you the log via email

**Comment by felixlen** [comment]
Date parsing is fixed now.

**Comment by daimpi** [comment]
Hey @felixlen thanks for this great tool 😊.

I'm under **Android** and I've found that when trying to check my log today, I still get shown "Invalid DateTime" and also the number of keys this package contains seemingly hasn't been parsed:
![grafik](https://user-images.githubusercontent.com/22129968/92308756-6108e480-efa0-11ea-90a7-f76272eb4e8c.png)

Additionally: under **iOS** the ENF log format [seems to have changed](https://github.com/corona-warn-app/cwa-app-ios/issues/1106#issuecomment-685486476) with iOS 13.7/14 and there also seems to be a problem with parsing the number of keys in a specific package under the new iOS version: 
![grafik](https://user-images.githubusercontent.com/22129968/92308815-c957c600-efa0-11ea-86df-68298090c385.png)
FYI: I've edited the logs, such that there would be one match on the most recent package in each log file by replacing the `0` in match count by `1` so that your tool would find something 🙂.  
- The logs for iOS and Android: [logs.zip](https://github.com/felixlen/ena_log/files/5178318/logs.zip)

Maybe you could reopen this issue for now? 🙂

**Comment by felixlen** [comment]
Hi @daimpi,

thanks for bringing this up. I will check the DateTime (unfortunately Android is not using ISO 8601 in their logs, which would make things much easier). I have updated parsing to iOS 13.7/14, but overlooked the keyCount and will also have a look into this.

Best
Felix

**Comment by felixlen** [comment]
@daimpi Should be fixed, could you please give a test and confirm?

**Comment by daimpi** [comment]
Yes I can confirm that it's fixed 👍. Thanks for the ultra fast reaction 😊. 

**Android**:
![grafik](https://user-images.githubusercontent.com/22129968/92309864-5a329f80-efa9-11ea-8726-ba5a8ffe7a82.png)

**iOS**:
![grafik](https://user-images.githubusercontent.com/22129968/92309882-720a2380-efa9-11ea-8f76-7826b721e97f.png)

**Comment by Optiligence** [comment]
i still get this with Language »English (United States)«: 
e.g. `"timestamp":"September 2, 2020, 11:18"`

but i noticed there is »English (Germany)«, with which it works
